// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_JSFVy99xo8h2-6nfIZEK4rXlMAOfX_o',
    appId: '1:549257021480:web:7454fc172361f10a9d4d1d',
    messagingSenderId: '549257021480',
    projectId: 'movieapplicayion',
    authDomain: 'movieapplicayion.firebaseapp.com',
    storageBucket: 'movieapplicayion.appspot.com',
    measurementId: 'G-241FGVLF9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8iE0lmMZEg5kEGWd5XHTbWk4_XfqRbw8',
    appId: '1:549257021480:android:af72d16dc058d7999d4d1d',
    messagingSenderId: '549257021480',
    projectId: 'movieapplicayion',
    storageBucket: 'movieapplicayion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvdDSYjIRJia86x5aenIqf5WMP5VLqSag',
    appId: '1:549257021480:ios:b5cd78a69b9948cc9d4d1d',
    messagingSenderId: '549257021480',
    projectId: 'movieapplicayion',
    storageBucket: 'movieapplicayion.appspot.com',
    iosBundleId: 'com.example.testmovieapp',
  );
}
